#!/bin/sh

configure_vim()
{
    ln -f .vimrc ~/
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    vim +PlugInstall +qall
}

configure_scmbreeze()
{
   git clone git://github.com/scmbreeze/scm_breeze.git ~/.scm_breeze
  ~/.scm_breeze/install.sh
  source ~/.zshrc
}

ln -f .zshrc ~/
configure_vim
configure_scmbreeze
